name: TModsServerAddons_DoubleJump
main: me.tmods.serveraddons.DoubleJump
version: 1.6
author: Timo Hocker
website: http://timosmods.weebly.com

depends:
 - TModsServerUtils
 
Permissions:
  ServerAddons.doubleJump
  ServerAddons.denyFallDamage