name: TModsServerAddons_DoubleJump
main: me.tmods.serveraddons.DoubleJump
version: 1.8
author: Timo Hocker
website: http://timosmods.weebly.com

depends:
 - TModsServerUtils
 
commands:
  toggleJump:
    description: toggle your DoubleJump
    usage: /toggleJump
 
Permissions:
  ServerAddons.doubleJump
  ServerAddons.denyFallDamage